### ISSUE TITLE
Option to change clock position

### ISSUE THREAD

**Issue by Ronin4862** [schorschii/FsClock-Android#16]
Hi,
Great app!
Please include a toggle button that randomly changes the position of the displayed info to prevent screen burn-in.
Regards

**Comment by joaocandre** [comment]
Alternatively, allow setting up ON/OFF intervals.

**Comment by batagy** [comment]
Hi!

This is great screensaver app. I would use on plasma TV, however due to burn-in of screen, I cannot use.

Feature request: 
Add option to move the clock randomly on the screen, to prevent screen burning on plasma and OLED TV's.
Also, there should be option to display smaller clock for the random movement option.

Thanks in advance
