### ISSUE TITLE
Huawei libs

### ISSUE THREAD

**Issue by IzzySoft** [schorschii/FsClock-Android#7]
Your app uses several libraries I couldn't figure out the licenses for, like

* [Huawei Update SDK](https://developer.huawei.com/consumer/en/)
* Huawei Mobile Services
* [HUAWEI In-App Purchases](https://developer.huawei.com/consumer/en/codelab/HMSInAppPurchase/index.html)

As your app is under a FOSS license (GPL), I just wondered if the same applies to the libraries used. Can you tell me what licenses the above libraries fall under?

Don't get me wrong: this is no "accusation" or something alike, but simple "information gathering" – so "pure human curiosity" if you want. So thank you in advance for telling me! If they don't name the license (which I assume, as I was unable to find those details), can you at least say (or point to) "terms" they claimed – like "if you use this SDK, you have to adhere to …")?

Oh, PS: if you want to add a 5th badge to the row on the Readme, [how about this](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) which you coud [link to here](https://apt.izzysoft.de/fdroid/index/apk/systems.sieber.fsclock)? :smiley:

**Comment by IzzySoft** [comment]
If I might amend the list: in today's update I spotted two additional entries.

* `/com/huawei/hmf/tasks` ([Huawei HMF Tasks](https://stackoverflow.com/tags/huawei-hmf-tasks/info))
* `/com/huawei/android/hms/base` (might fall into Huawei Mobile Services again)

**Comment by schorschii** [comment]
Hi IzzySoft,

I just completely refactored the way the app includes the store libraries with version 1.8.0 using build flavors: Amazon and Huawei libs are now only included in specific builds (as enforced by Google because apps on Google Play cannot contain the Huawei SDK anymore). And now, I remembered your issue and want to answer. Sorry for the long delay.

Those libraries do not have an open source license. I don't think this is a problem since they are not directly part of my repo, only linked in the gradle dependencies. In addition to that, although if they are not open, they are permissive:

The Amazon SDK, as can be found on the [Maven repo](https://search.maven.org/artifact/com.amazon.device/amazon-appstore-sdk/3.0.3/jar), is licensed under a custom license called [Program Materials License](https://developer.amazon.com/support/legal/pml). This license says clearly:
>  [...] you may incorporate those materials in Your Products and reproduce and distribute those Program Materials as incorporated in Your Products. You may also modify any such source code to the extent necessary to incorporate it in Your Products.

The Google Play Billing SDK, as stated in the metadata file `~/.gradle/caches/modules-2/files-2.1/com.android.billingclient/billing/5.0.0/.../billing-5.0.0.pom`, links to the [Android Software Development Kit License](https://developer.android.com/studio/terms.html), a rather generic permissive license for the entire Android project.

For the Huawei libs, it is indeed not that easy to tell. I think they simply forgot to declare a license on their SDK because no one really cares. The from https://developer.huawei.com/repo/ downloaded packages do not contain any license information. I was also not able to find anything on the web, thats why I asked the Huawei support, and this was their response (no joke):
> We do not have the license information you are looking for. There is no problem in integrating it into your open source application.

Maybe this some kind of answered your question?

Georg

**Comment by IzzySoft** [comment]
Thanks for your reply, @schorschii – and let me clarify:

> Those libraries do not have an open source license.

So having them in an app means that app is not entirely open/libre either. Nor is the PML open-source as it restricts in which ways you can use the code:

> to the extent necessary to incorporate it in Your Products.

Reading between the lines, the "incorporate" here most likely means "to make your products work with out services", so it's always bound to them. I might be wrong here (and have no time to investigate), but I doubt the "4 freedoms" are guaranteed.

> There is no problem in integrating it into your open source application.

That's what you hear in several places – but there is: if you put poison into food, the food is poisoned (sounds a bit exaggerated, but like with satire it's for the purpose to carry over the idea: your software gets tainted). No license being declared means "all rights reserved". So places like F-Droid cannot build your app.

The above is just for clarification, not "accusing" or anything like that. If your app cannot work without those, there's nothing you can do. But if it can, such a F/LOSS build flavor would be very welcome!
